# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # host: localhost # Specify the database host (localhost for local development)

development:
  <<: *default
  database: Felp_development
  # username: Felp # Specify your PostgreSQL username if needed
  # password: <%= ENV['FELP_DATABASE_PASSWORD'] %>
  # port: 3000 # Specify the database port if it's not the default (5432)

test:
  <<: *default
  database: Felp_test

production:
  <<: *default
  database: Felp_production
  username: Felp
  password: <%= ENV['FELP_DATABASE_PASSWORD'] %>
